config/routes.rb
Rails.application.routes.draw do
  root "sessions#new"

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"

  get "/signup", to: "users#new"
  post "/signup", to: "users#create"

  resources :notes, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true
  validates :password, length: { minimum: 6 }, if: -> { password.present? }

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

   def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def authenticate_user!
    redirect_to login_path, alert: "You must be logged in to access this page" unless current_user
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!

  def index
    @notes = current_user.notes
  end

  def new
    @note = Note.new
  end

  def create
    @note = current_user.notes.build(note_params)
    if @note.save
      redirect_to notes_path, notice: "Note created successfully"
    else
      render :new
    end
  end

  private

  def note_params
    params.require(:note).permit(:title, :message)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to notes_path, notice: "Logged in successfully"
    else
      flash.now[:alert] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_path, notice: "Logged out successfully"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to notes_path, notice: "Account created successfully"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Testapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/create.html.erb
<h1>Notes#create</h1>
<p>Find me in app/views/notes/create.html.erb</p>

app/views/notes/index.html.erb
<h1>Your Notes</h1>

<%= link_to "Create New Note", new_note_path %>
<%= link_to "Logout", logout_path, method: :delete %>

<ul>
  <% @notes.each do |note| %>
    <li><strong><%= note.title %></strong>: <%= note.message %></li>
  <% end %>
</ul>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= form_with model: @note do |form| %>
  <p>Title: <%= form.text_field :title %></p>
  <p>Message: <%= form.text_area :message %></p>
  <%= form.submit "Create Note" %>
<% end %>

<%= link_to "Back to Notes", notes_path %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_with model: @user, url: signup_path do |form| %>
  <p>Email: <%= form.email_field :email %></p>
  <p>Password: <%= form.password_field :password %></p>
  <p>Confirm Password: <%= form.password_field :password_confirmation %></p>
  <%= form.submit "Sign Up" %>
<% end %>

<p>Already have an account? <%= link_to "Login", login_path %></p>